"""Phase 1 audit of the TP002.1 register workbook.

Reads every sheet and writes ``docs/data-audit-inventory.md``: the machine-
generated evidence behind ``docs/data-audit.md`` (row classifications, column
fill counts, distinct values, hyperlinks, comments, whitespace quirks).

Usage:
    python import/audit_workbook.py [path/to/register.xlsx] [output.md]
"""

from __future__ import annotations

import sys
import warnings
from collections import Counter, defaultdict
from pathlib import Path

import openpyxl

sys.path.insert(0, str(Path(__file__).resolve().parent))
import tp002_layout as L  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
DEFAULT_XLSX = REPO / "source" / "DTI-HSEQ-TP002.1_Environmental_Compliance_Obligations_Register_Rev2_DRAFT_DH.xlsx"
DEFAULT_OUT = REPO / "docs" / "data-audit-inventory.md"

INVENTORY_FIELDS = ["stage", "status", "due", "timing", "responsibility", "risk"]


def md_escape(value, limit: int = 120) -> str:
    if value is None:
        return ""
    text = value.isoformat()[:10] if hasattr(value, "isoformat") else str(value)
    text = text.replace(L.NBSP, "\u2423")  # show NBSP as a visible open-box
    text = text.replace("|", "\\|").replace("\n", " \u23ce ").replace("\t", "\u21e5")
    return text if len(text) <= limit else text[: limit - 1] + "\u2026"


def row_values(ws, r: int, columns: dict[str, str]) -> dict:
    return {fld: ws[f"{col}{r}"].value for col, fld in columns.items()}


def classify(ws, r: int, block: L.Block, header_texts: set[str]) -> tuple[str, str]:
    """Return (class, reason) for one row inside a block's range."""
    raw = row_values(ws, r, block.columns)
    cleaned = {k: L.clean_text(v) for k, v in raw.items()}
    filled = {k: v for k, v in cleaned.items() if v is not None}
    if not filled:
        has_nbsp = any(isinstance(v, str) and v.strip(" \u00a0") == "" and v for v in raw.values())
        return "blank", "only non-breaking spaces" if has_nbsp else ""
    if {str(v).strip() for v in filled.values()} <= header_texts:
        return "repeated-header", ""
    if block.hidden:
        if set(filled) == {"location"}:
            return "legacy-stub", f"only '{filled['location']}' in column A (hidden row)"
        return "legacy-hidden", "hidden legacy approval summary row"
    if L.is_info_only(cleaned):
        return "info-only", "Note/Noted in action, responsibility or status"
    if (filled.get("condition_no") and not filled.get("location") and not filled.get("stage")):
        return "sub-condition", f"condition {filled['condition_no']} continues the row above"
    req = filled.get("requirement")
    if req is None:
        return "flag", "no requirement text"
    if isinstance(req, str) and len(req) < 5:
        return "flag", f"requirement is a placeholder ({req!r})"
    return "obligation", ""


def main(xlsx: Path, out: Path) -> None:
    warnings.simplefilter("ignore")  # openpyxl drops x14 validation/CF extensions noisily
    wb = openpyxl.load_workbook(xlsx)
    lines: list[str] = []
    w = lines.append

    w("# Data audit - machine inventory")
    w("")
    w(f"Generated by `import/audit_workbook.py` from `{xlsx.name}`. Do not edit by hand; "
      "re-run the script. The narrative and decisions are in `data-audit.md`.")
    w("")
    w("Legend: `\u23ce` = line break inside a cell, `\u2423` = non-breaking space, `\u21e5` = tab.")
    w("")

    # ---- Sheet overview -------------------------------------------------
    w("## 1. Sheets")
    w("")
    w("| # | Sheet | Kind | Used range | Hidden rows | Hidden cols | Purpose |")
    w("|---|---|---|---|---|---|---|")
    for i, ws in enumerate(wb.worksheets, 1):
        spec = L.SHEETS_BY_NAME[ws.title]
        hidden_rows = [r for r, d in ws.row_dimensions.items() if d.hidden]
        hidden_cols = [c for c, d in ws.column_dimensions.items() if d.hidden]
        hr = f"{hidden_rows[0]}-{hidden_rows[-1]}" if hidden_rows else ""
        w(f"| {i} | {ws.title} | {spec.kind} | {ws.dimensions} | {hr} | {', '.join(hidden_cols)} | {md_escape(spec.purpose, 200)} |")
    w("")

    # ---- Per obligation sheet -------------------------------------------
    inventory: dict[str, Counter] = defaultdict(Counter)
    quirk_counts: dict[str, Counter] = defaultdict(Counter)
    class_totals: dict[str, Counter] = defaultdict(Counter)

    w("## 2. Obligation sheets - headers, fill counts and row classification")
    w("")
    for spec in L.SHEETS:
        if spec.kind != "obligations":
            continue
        ws = wb[spec.name]
        w(f"### {spec.name}")
        w("")
        for bi, block in enumerate(spec.blocks, 1):
            header_texts = {str(c.value).strip() for c in ws[block.header_row] if c.value is not None}
            title = f"Block {bi}: header row {block.header_row}, rows {block.first_row}-{block.last_row}"
            if block.context:
                title += " - " + ", ".join(f"{k}={v}" for k, v in block.context.items())
            if block.hidden:
                title += " (HIDDEN)"
            w(f"**{title}**" + (f" - {block.note}" if block.note else ""))
            w("")
            w("| Col | Row-4 group | Row-5 header | Maps to | Filled |")
            w("|---|---|---|---|---|")
            for col, fld in block.columns.items():
                hdr = ws[f"{col}{block.header_row}"].value
                grp = ws[f"{col}{L.GROUP_HEADER_ROW}"].value if block.header_row == L.HEADER_ROW else ""
                filled = sum(1 for r in range(block.first_row, block.last_row + 1)
                             if L.clean_text(ws[f"{col}{r}"].value) is not None)
                w(f"| {col} | {md_escape(grp)} | {md_escape(hdr) or '_(no header)_'} | `{fld}` | {filled} |")
            w("")
            w("| Row | Class | Reason / first 70 chars of requirement |")
            w("|---|---|---|")
            for r in range(block.first_row, block.last_row + 1):
                cls, reason = classify(ws, r, block, header_texts)
                class_totals[spec.name][cls] += 1
                if cls == "blank" and not reason:
                    continue
                req = row_values(ws, r, block.columns).get("requirement")
                w(f"| {r} | {cls} | {md_escape(reason) or md_escape(req, 70)} |")
                if cls in ("obligation", "info-only", "sub-condition", "flag", "legacy-hidden"):
                    vals = row_values(ws, r, block.columns)
                    for fld in INVENTORY_FIELDS:
                        v = vals.get(fld)
                        if L.clean_text(v) is not None:
                            key = v.date().isoformat() if hasattr(v, "date") else L.clean_text(v)
                            inventory[fld][(key, spec.name)] += 1
            w("")
        # Header rows repeated mid-sheet (one per decision notice block)
        for block in spec.blocks:
            if block.header_row != L.HEADER_ROW:
                class_totals[spec.name]["repeated-header"] += 1
        # Rows outside all blocks that still hold content (group rows etc.)
        in_blocks = {r for b in spec.blocks for r in range(b.header_row, b.last_row + 1)}
        extra = []
        for r in range(L.FIRST_DATA_ROW, ws.max_row + 1):
            if r in in_blocks:
                continue
            vals = [c for c in ws[r] if L.clean_text(c.value) is not None]
            if vals:
                extra.append((r, " \u00b7 ".join(f"{c.column_letter}={md_escape(c.value, 80)}" for c in vals)))
        if extra:
            w("Rows outside the data blocks that hold content:")
            w("")
            for r, text in extra:
                w(f"- Row {r}: {text}")
                class_totals[spec.name]["group-row"] += 1
            w("")

        # Cell-level quirks across the whole sheet
        for row in ws.iter_rows(min_row=L.FIRST_DATA_ROW):
            for c in row:
                v = c.value
                if not isinstance(v, str):
                    continue
                q = quirk_counts[spec.name]
                if L.NBSP in v:
                    q["nbsp" if v.strip(" \u00a0") else "nbsp-only"] += 1
                if "\n" in v.strip():
                    q["multi-line"] += 1
                if v != v.strip():
                    q["leading/trailing whitespace"] += 1
                if v.startswith("\t"):
                    q["leading tab"] += 1
                if L.CITATION_RE.search(v):
                    q["pasted citation"] += 1

    # ---- Totals -----------------------------------------------------------
    w("## 3. Row classification totals")
    w("")
    classes = ["obligation", "sub-condition", "info-only", "flag", "legacy-hidden",
               "legacy-stub", "repeated-header", "group-row", "blank"]
    w("| Sheet | " + " | ".join(classes) + " |")
    w("|---|" + "---|" * len(classes))
    grand = Counter()
    for sheet, cnt in class_totals.items():
        grand.update(cnt)
        w(f"| {sheet} | " + " | ".join(str(cnt.get(c, 0)) for c in classes) + " |")
    w("| **Total** | " + " | ".join(f"**{grand.get(c, 0)}**" for c in classes) + " |")
    w("")

    w("## 4. Cell quirks (data rows only)")
    w("")
    qkeys = ["multi-line", "leading/trailing whitespace", "nbsp", "nbsp-only", "leading tab", "pasted citation"]
    w("| Sheet | " + " | ".join(qkeys) + " |")
    w("|---|" + "---|" * len(qkeys))
    for sheet, cnt in quirk_counts.items():
        w(f"| {sheet} | " + " | ".join(str(cnt.get(k, 0)) for k in qkeys) + " |")
    w("")

    # ---- Distinct values --------------------------------------------------
    w("## 5. Distinct values (obligation, info-only, sub-condition, flagged and legacy rows)")
    w("")
    for fld in INVENTORY_FIELDS:
        w(f"### `{fld}`")
        w("")
        w("| Count | Sheet | Value |")
        w("|---|---|---|")
        for (value, sheet), n in sorted(inventory[fld].items(), key=lambda kv: (str(kv[0][0]).lower(), kv[0][1])):
            w(f"| {n} | {sheet} | {md_escape(value, 200)} |")
        w("")

    # ---- Hyperlinks ---------------------------------------------------------
    w("## 6. Hyperlinks")
    w("")
    w("Relative targets are resolved against the tenant host by `resolve_hyperlink()`.")
    w("")
    w("| Cell | Display text | Resolved URL |")
    w("|---|---|---|")
    for ws in wb.worksheets:
        for row in ws.iter_rows():
            for c in row:
                if c.hyperlink:
                    target = c.hyperlink.target or c.hyperlink.location
                    w(f"| {ws.title}!{c.coordinate} | {md_escape(c.value, 60)} | {md_escape(L.resolve_hyperlink(target), 160)} |")
    w("")

    # ---- Comments -----------------------------------------------------------
    w("## 7. Cell comments")
    w("")
    w("| Cell | Comment |")
    w("|---|---|")
    for ws in wb.worksheets:
        for row in ws.iter_rows():
            for c in row:
                if c.comment:
                    text = c.comment.text
                    if "Comment:" in text:  # threaded comment fallback text
                        text = text.split("Comment:", 1)[1]
                    w(f"| {ws.title}!{c.coordinate} | {md_escape(' '.join(text.split()), 220)} |")
    w("")

    # ---- Reference sheets ---------------------------------------------------
    w("## 8. Reference sheets")
    w("")
    for name in ["Summary", "Reporting Matrix", "_Doc Ref"]:
        ws = wb[name]
        w(f"### {name}")
        w("")
        for row in ws.iter_rows():
            vals = [c for c in row if c.value is not None]
            if not vals:
                continue
            red = any(c.font and c.font.color is not None and c.font.color.rgb == "FFFF0000" for c in vals)
            text = " \u00b7 ".join(f"{c.column_letter}={md_escape(c.value, 90)}" for c in vals)
            w(f"- Row {row[0].row}{' **(red text)**' if red else ''}: {text}")
        w("")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(REPO) if out.is_relative_to(REPO) else out}")
    for sheet, cnt in class_totals.items():
        print(f"  {sheet}: {dict(cnt)}")


if __name__ == "__main__":
    xlsx = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_XLSX
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    main(xlsx, out)
